development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: qb
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: qb
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

